server:
  port: 8080

spring:
  application:
    name: RabbitMQ_04_DLX

  #rabbitmq
  rabbitmq:
    host: 192.168.15.129
    port: 5672
    username: admin
    password: 123abc
    virtual-host: testing

my:
  exchangeNormal: exchange.Normal.a
  queueNormal: queue.Normal.a

  exchangeDead: exchange.Dead.a
  queueDead: queue.Dead.a
