spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: 123abc
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.MrLi.admin.*
      filters: stat,wall,slf4j
  #配置redis
  redis:
    url: redis://user:password@example.com:6379
    client-type: jedis
    jedis:
      pool:
        max-active: 10

# management 是所有监控指标 Actuator 的配置
management:
  endpoints:
    enabled-by-default: true # 默认开启所有的监控端点
    web:
      exposure:
        include: '*' # 以web方式暴露所有的监控端点