#端口名
server:
  port: 8088
#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/part_time?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: 123abc
      driver-class-name: com.mysql.cj.jdbc.Driver
  #文件上传
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  main:
    #消除依赖循环引用
    allow-circular-references: true
    #覆盖 bean
    allow-bean-definition-overriding: true
  #redis 配置
  redis:
    host: 192.168.200.129
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 86400000
#mybatis-plus
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
#七牛云配置
oss:
  accessKey: HMO7QFDVyUkyPqaBy1RVklcJyrc2iS9yv_-I38SF
  secretKey: uGOFAUmjs2ugR1JeopjRvYmG5eHqtMAHlxzv7JwT
  bucket: lilinblog
  domainName: rhzfc57ag.hn-bkt.clouddn.com