
spring:
  datasource:
    url: jdbc:mysql:///3306/book
    username: root
    password: 123abc
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      #开启底层filter功能 stat：sql监控 wall：防火墙
      filters: stat,wall

      #配置监控页功能
      stat-view-servlet:
        login-username: root
        login-password: 123abc
        reset-enable: false

      #监控web
      web-stat-filter:
        enabled: true
        url-pattern: /*

      #监控springBean
      aop-patterns: com.MrLi.demo.*

      #对上面filters里面的stat、wall的详细配置
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  #配置redis
  redis:
    url: redis://user:password@example.com:6379
    client-type: jedis
    jedis:
      pool:
        max-active: 10

mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true