server:
  port: 8080

spring:
  application:
    name: RabbitMQ_03_TTL2

  #rabbitmq
  rabbitmq:
    host: 192.168.15.129
    port: 5672
    username: admin
    password: 123abc
    virtual-host: testing

my:
  exchangeName: exchange.ttl.b
  queueName: queue.ttl.b
